[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 10000
bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 64
fail_on_revert = false

